config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'estimate', to: 'estimates#new', as: 'new_estimate'
  resources :estimates, only: [:create]
  get "/settings" => "settings#index"

  devise_for :admins
  as :admin do
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :photos
  resources :testimonials
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @photos = Photo.all
    @testimonials = Testimonial.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row" id='lead'>
  <div class="container">
    <div class='col-xs-12 col-sm-12 col-md-6'>
      <%= image_tag("mip_logo.jpg", size: '920x200', class: 'img-responsive img-rounded img-thumbnail center') %>
    </div>
    <div class='col-xs-12 col-sm-12 col-md-6'>
      <p id='tagline'>Owner Mark Centola has over 30 years of painting experience and has been providing quality and affordable painting to Massachusetts and New Hampshire for <em>11</em> years!
      </p>
      <p id='motto' class='center'>Whether it's a wall or a mall, we'll paint it all!
      </p>
    </div>
  </div>
</div>

<div id="services" class="scroll-buffer"> </div>
<div class="center">
  <div class="services-bar">
    <h1 class='title'>Services</h1>
    <p>( Residential - Commercial - Industrial )</p>
  </div>
  <div class='row'>
    <div class='col-xs-6 col-sm-6 col-md-6 col-lg-6'>
      <div class="list-group">
        <span class="list-group-item active">Interior Painting</span>
        <span class="list-group-item">Walls</span>
        <span class="list-group-item">Accents</span>
        <span class="list-group-item">Ceilings</span>
        <span class="list-group-item">Trim</span>
      </div>
    </div>
    <div class='col-xs-6 col-sm-6 col-md-6 col-lg-6'>
      <div class="list-group">
        <span class="list-group-item active">Exterior Painting</span>
        <span class="list-group-item">Siding</span>
        <span class="list-group-item">Trim</span>
        <span class="list-group-item">Decks (including powerwashing)</span>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-12 col-sm-6 col-md-6 col-lg-6'>
      <div class="list-group">
        <span class="list-group-item active">Prep and Miscellaneous</span>
        <span class="list-group-item">Wall Cleaning</span>
        <span class="list-group-item">Wall Paper Removal</span>
        <span class="list-group-item">Wall/Ceiling Repair</span>
      </div>
    </div>
    <div class='col-xs-12 col-sm-6 col-md-6 col-lg-6'>
      <div class="list-group">
        <span class="list-group-item active">Options</span>
        <span class="list-group-item">Brush, Roller, or Spray</span>
        <span class="list-group-item">Color Selection Assistance</span>
        <span class="list-group-item">Night Painting Available</span>
      </div>
    </div>
    <div class='col-xs-12 col-md-12 col-lg-12 free-estimate-bar'>
      <p>
        <strong id='estimate'>
          <%= link_to "Request a Free Estimate!", new_estimate_path, class: 'free-estimates btn btn-success' %><br />
        </strong>
      </p>
    </div>
  </div>
</div>

<div id="testimonials" class="scroll-buffer"> </div>
<div class="center">
  <div class="testimonial-bar">
    <h1 class='title'>Testimonials</h1>
    <p>( What our customers are saying! )</p>
  </div>
  <div class="container">
    <div class="row">
      <% @testimonials.each do |t| %>
      <div class="col-xs-12 col-md-6 col-lg-6">
        <blockquote>
          <p><%= t.content %></p>
          <footer><%= t.customer_name %></footer>
        </blockquote> 
      </div>
      <% end %>
    </div>
  </div>
</div>

<div id="gallery" class="scroll-buffer"> </div>
<div class="center">
  <div class="gallery-bar">
    <h1 class='title'>Gallery</h1>
    <p>( Recently Completed Work )</p>
  </div> 
  <div class="galleria img-responsive center"> 
    <% if @photos.empty? %>
      <strong>Please add photos for the gallery.</strong>
    <% else %>
      <% @photos.each do |p| %>
        <%= image_tag p.image.url(:normal), title: p.title, alt: p.description %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="scroll-buffer" id="contact"> </div>
<div class="center">
  <div class="contact-bar">
    <h1 class='title'>Contact Us</h1>
    <p>( Call for a free consultation and estimate! )</p>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <p id='call-us'>Please give us a call at <a href="tel:1-617-968-4000"><%= fa_icon "phone" %>&nbsp;1-617-968-4000</a> to schedule a free consultation and estimate.</p>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript"> 
$('.galleria').galleria({
});

Galleria.configure({
  theme: 'classic',
  imageCrop: true,
  autoplay: 2500,
  lightbox: true,
  responsive: true,
  transition: 'pan',
  transitionSpeed: 800,
  thumbCrop: 'height',
  idleMode: 'hover',
  idleSpeed: 500,
  fullscreenTransition: true
});
Galleria.run('.galleria');
</script>