config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'estimate', to: 'estimates#new', as: 'new_estimate'
  resources :estimates, only: [:create]
  get "/settings" => "settings#index"

  devise_for :admins
  as :admin do
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :photos
  resources :testimonials
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, styles: { normal: "2000x2000>", small: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :title, uniqueness: true
  validates_presence_of :title, :description, :image
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(photo_params)
    if @photo.save
      redirect_to @photo
    else
      render :new
      flash[:notice] = "You have errors."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy!
    redirect_to photos_path
  end
  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :description, :image)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-8">
    <h2>Add a Photo</h2>
    <%= simple_form_for @photo, html: { class: 'text-left jumbotron' } do |f| %>
      <%= f.input :title, placeholder: "Fresh Paint!" %>
      <%= f.input :description, placeholder: "Love the smell of fresh new paint on the walls!" %>
      <%= f.input :image %>
      <%= f.button :submit, class: 'btn btn-success' %>
      <p></p>
      <%= link_to "Cancel", photos_path, class: 'btn btn-danger' %>
    <% end %>
  </div>
  <div class="col-sm-2">
  </div>
</div>
<p></p>

app/views/photos/edit.html.erb
<div class="row">
  <div class="container">
    <div class="col-xs-3 col-sm-3 col-md-3">
      <p>Current Photo</p>
      <%= image_tag @photo.image.url(:small), class: 'img-thumbnail' %>
    </div>
    <div class="col-xs-7 col-sm-6 col-md-6" id='edit_photo_form'>
      <h1>Edit Photo</h1>
      <%= render 'form' %>
      <%= link_to "Cancel Edit", photos_path, class: 'btn btn-danger', id: 'cancel-photo-edit' %>
    </div>

  </div>
</div>

app/views/photos/index.html.erb
<h3>All Photos</h3>
<%= link_to fa_stacked_icon("plus", base: "square-o") + " Add Photo", new_photo_path %>

<div class="row well" id="all-photos">
  <% @photos.each do |photo| %>
    <div class="col-xs-4 col-md-2" id="each-photo">
      <a href='<%= photo_path(photo) %>' alt='<%= photo.title %>'><%= image_tag photo.image.url(:thumb), class: 'img-thumbnail img-responsive' %></a>
    </div>
  <% end %>
</div>
<%= link_to "Back", settings_path, class: 'btn btn-primary' %>

app/views/photos/new.html.erb
<%= render "form" %>

app/views/photos/show.html.erb
<div class="center">
  <p>
  <%= image_tag @photo.image.url(:small), class: 'img-responsive img-thumbnail', alt: @photo.title %>
  </p>

  <div class='jumbotron'>
    <%= @photo.title %>
    <br />
    <%= @photo.description %>
  </div>

  <p>
  <%= link_to fa_icon('arrow-circle-o-left') + " All Photos", photos_path, class: 'btn btn-primary' %>
  <%= link_to "Edit Photo", edit_photo_path, class: "btn btn-info" %>
  <%= link_to "Delete Photo", @photo, method: :delete, data: { confirm: "Are you sure" }, class: 'btn btn-danger' %>
  </p>
</div>