config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'estimate', to: 'estimates#new', as: 'new_estimate'
  resources :estimates, only: [:create]
  get "/settings" => "settings#index"

  devise_for :admins
  as :admin do
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
    get "/logout" => "devise/sessions#destroy"
  end

  resources :photos
  resources :testimonials
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates_presence_of :content, :customer_name
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_testimonial, only: [:show,:edit,:destroy]

  def index
    @testimonials = Testimonial.all
  end

  def show
  end

  def edit
  end

  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = Testimonial.create(testimonial_params)

    if @testimonial.save
      redirect_to @testimonial
    else
      render :new
    end
  end

  def update

    @testimonial = Testimonial.find(set_testimonial)
    if @testimonial.update_attributes(testimonial_params)
      redirect_to @testimonial
    else
      render :edit
    end
  end

  def destroy
    @testimonial.destroy!
    redirect_to testimonials_path
  end

  private

  def set_testimonial
    @testimonial = Testimonial.find(params[:id])
  end

  def testimonial_params
    params.require(:testimonial).permit(:content, :customer_name)
  end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<div class="col-sm-2">
</div>
<div class="col-sm-8">
  <h2>Add a Testimonial</h2>
  <%= simple_form_for @testimonial, html: { class: 'text-left jumbotron' } do |f| %>
    <%= f.input :customer_name %>
    <%= f.input :content %>
    <%= f.submit class: 'btn btn-success' %>
    <p></p>
    <%= link_to "Cancel", testimonials_path, class: 'btn btn-danger' %>
  <% end %>
</div>
<div class="col-sm-2">
</div>

app/views/testimonials/edit.html.erb
<div class="row">
  <div class="container">
    <div class="col-xs-12" id='edit_testimonial_form'>
      <h1>Edit Testimonial</h1>
      <%= render 'form' %>
      <br />
      <%= link_to "Cancel Edit", testimonials_path, class: 'btn btn-danger', id: 'cancel-testimonial-edit' %>
    </div>

  </div>
</div>

app/views/testimonials/index.html.erb
<h3>All Testimonials</h3>
<%= link_to fa_stacked_icon("plus", base: "square-o") + " Add Testimonial", new_testimonial_path %>

<div class="row well" id="all-testimonials">
  <% @testimonials.each do |t| %>
    <div class="col-xs-12">
      <a href='<%= testimonial_path(t) %>' alt='<%= t.customer_name %>'><%= t.customer_name + " Testimonial" %></a>
    </div>
  <% end %>
</div>
<%= link_to "Back", settings_path, class: 'btn btn-primary' %>

app/views/testimonials/new.html.erb
<%= render 'form' %>

app/views/testimonials/show.html.erb
<blockquote>
  <p>
  <span class="testimonial-content"><%= @testimonial.content %></span>
  </p>
  <footer><%= @testimonial.customer_name %></footer>
</blockquote> 
<%= link_to fa_icon('arrow-circle-o-left') + " All Testimonials", testimonials_path, class: 'btn btn-primary' %>
<%= link_to "Edit Testimonials", edit_testimonial_path, class: "btn btn-info" %>
<%= link_to "Delete Testimonial", @testimonial, method: :delete, data: { confirm: "Are you sure" }, class: 'btn btn-danger' %>
</p>